apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cadvisor.yaml
  - ../base/client.yaml
  - ../base/esx-ntp-config.yaml
  - ../base/k8s-dashboard.yaml
  - ../base/linux-ubuntu-vm.yaml
  - ../base/podinfo-kustomization.yaml
  - ../base/podinfo-source.yaml
  - ../base/web-server.yaml
  - ../base/ww-gitops-dashboard.yaml
